name: Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'resources.zip'
        path: './resourcepack'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "resources.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
