name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set version
      id: name
      run: |
        REPOSITORY=$(echo ${{ github.repository }} | sed -e 's#.*/##')
        echo ::set-output name=name::$REPOSITORY
        echo ::set-output name=resources::$REPOSITORY-resources
        echo ::set-output name=datapack::$REPOSITORY-datapack
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        directory: 'resourcepack'
        filename: '${{ steps.name.outputs.resources }}.zip'
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        directory: 'datapack'
        filename: '${{ steps.name.outputs.datapack }}.zip'
    - name: checksum
      id: checksum
      run: |
        resources_checksum=$(sha1sum resourcepack/${{ steps.name.outputs.resources }}.zip)
        echo ::set-output name=resources::$resources_checksum
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'resourcepack/${{ steps.name.outputs.resources }}.zip,datapack/${{ steps.name.outputs.datapack }}.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        body: 'sha1: ${{ steps.checksum.outputs.resources }}'
