name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        directory: 'resourcepack'
        filename: 'resources.zip'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'resources.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
